name: Contracts CI/CD
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}
    - run: .github/scripts/docker-build.sh . docker.pkg.github.com/promaty/govern/test $GITHUB_SHA

  coverage:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/promaty/govern/test:${{github.sha}}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    needs: build
    steps:
    - name: Run coverage
      run: cd /app && yarn coverage
    - name: Upload report
      run: cd /app && curl -s https://codecov.io/bash | bash
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # deploy-rinkeby:
  #   runs-on: ubuntu-latest
  #   container: aragon/govern:${{github.sha}}
  #   needs: coverage
  #   env:
  #     CD: true
  #     ETH_KEY: ${{ secrets.ETH_KEY }}
  #     ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
  #     REGISTRY_RINKEBY: "0x0cd3621EC403F26ad9F79c3d77B1dda1f8474c6f"
  #   steps:
    
  #   - name: Deploy Factory
  #     run: cd /app/packages/govern-create && yarn deploy-factory --network rinkeby

  #   - name: Deploy Govern
  #     run: cd /app/packages/govern-create && yarn deploy-govern --network rinkeby > github-message

  #   - name: Log
  #     run: cat /app/packages/govern-create/github-message
